apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: skgupta77159githubio-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skgupta77159githubio-react-app
  template:
    metadata:
      labels:
        app: skgupta77159githubio-react-app
    spec:
      containers:
        - name: sushil-react-app
          image: skgupta77159/skgupta77159githubio-react-app:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: skgupta77159githubio-react-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 31110
